# Generated by alias-manager

# Group: default
alias hello='echo '"'"'Hello World'"'"''
alias clear='clear'

# Group: git
alias gst='git status'
alias gadd='git add .'
alias gcommit='git commit -m "$*"'
alias gpush='git push'

# Group: docker
alias dps='docker ps'
alias dlog='docker logs -f'

# Group: system
alias ll='ls -la'
alias la='ls -A'
alias ..='cd ..'
